from __future__ import annotations

# Threshold contract metadata (frozen location per master spec).
version_id = "v1.0.0"
threshold_source = "Google Search Central 2024-03 (placeholder)"

# Placeholder citation URL registry.
CITATION_URLS: dict[str, str] = {
    "search_titles_guidance": "https://example.com/citations/search-titles-guidance",
    "core_web_vitals": "https://example.com/citations/core-web-vitals",
    "gbp_reviews": "https://example.com/citations/gbp-reviews",
}

# Placeholder threshold constants for deterministic diagnostics.
CTR_LOW_THRESHOLD = 0.02
HIGH_IMPRESSIONS_THRESHOLD = 1000
CTR_POSITION_MIN_THRESHOLD = 3.0
CTR_POSITION_MAX_THRESHOLD = 8.0
CTR_COMPETITOR_GAP_THRESHOLD = 0.015

LCP_THRESHOLD_SECONDS = 2.5
CLS_THRESHOLD = 0.1
INP_THRESHOLD_MS = 200
TTFB_THRESHOLD_MS = 800
CWV_SEVERITY_CAP = 2.0
CWV_LCP_WEIGHT = 0.35
CWV_CLS_WEIGHT = 0.2
CWV_INP_WEIGHT = 0.25
CWV_TTFB_WEIGHT = 0.2
CWV_BASE_CONFIDENCE = 0.5
CWV_CONFIDENCE_MULTIPLIER = 0.5

GBP_REVIEW_VELOCITY_THRESHOLD = 2.0
GBP_REVIEW_RESPONSE_RATE_THRESHOLD = 0.6
GBP_COMPETITOR_REVIEW_COUNT_GAP_THRESHOLD = 25.0

RANKING_POSITION_DROP_THRESHOLD = 2.0
RANKING_SEVERE_POSITION_DROP_THRESHOLD = 6.0
RANKING_TRAFFIC_DECLINE_THRESHOLD = -0.05
RANKING_SEVERE_TRAFFIC_DECLINE_THRESHOLD = -0.2

COMPETITOR_REQUIRED_SIGNAL_MIN_COUNT = 2
COMPETITOR_RATING_GAP_THRESHOLD = 0.3
COMPETITOR_POSITION_GAP_THRESHOLD = 3.0

DIAGNOSTIC_CONFIDENCE_LOW = 0.55
DIAGNOSTIC_CONFIDENCE_MEDIUM = 0.7
DIAGNOSTIC_CONFIDENCE_HIGH = 0.85
LOW_PRIORITY_SIGNAL_MAGNITUDE = 0.1
MEDIUM_PRIORITY_SIGNAL_MAGNITUDE = 0.5
HIGH_PRIORITY_SIGNAL_MAGNITUDE = 0.8
