"""add tier and billing fields to organizations

Revision ID: 009c09f3c436
Revises: 20260302_0042
Create Date: 2026-03-03 10:58:31.328267
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '009c09f3c436'
down_revision = '20260302_0042'
branch_labels = None
depends_on = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tier_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tier_code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('entitlement_template_json', sa.JSON(), nullable=False),
    sa.Column('deterministic_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deterministic_hash', name='uq_tier_profile_hash'),
    sa.UniqueConstraint('tier_code', 'version', name='uq_tier_profile_code_version')
    )
    op.create_index('ix_tier_profile_tier_code', 'tier_profiles', ['tier_code'], unique=False)
    op.create_table('entitlements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('value_type', sa.Enum('integer', 'boolean', 'unlimited', name='entitlement_value_type', native_enum=False), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=True),
    sa.Column('reset_period', sa.Enum('none', 'daily', 'monthly', name='entitlement_reset_period', native_enum=False), nullable=False),
    sa.Column('is_enforced', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('deterministic_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("((value_type = 'unlimited' AND limit_value IS NULL) OR (value_type != 'unlimited' AND limit_value IS NOT NULL))", name='ck_entitlements_limit_value_matches_type'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_entitlements_org_code')
    )
    op.create_index('ix_entitlements_org_code', 'entitlements', ['organization_id', 'code'], unique=False)
    op.create_index('ix_entitlements_organization_id', 'entitlements', ['organization_id'], unique=False)
    op.create_table('onboarding_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('last_transition_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deterministic_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', name='uq_onboarding_state_org')
    )
    op.create_index('ix_onboarding_state_organization_id', 'onboarding_states', ['organization_id'], unique=False)
    op.create_table('usage_ledgers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('entitlement_code', sa.String(length=120), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_value', sa.Integer(), nullable=False),
    sa.Column('deterministic_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'entitlement_code', 'period_start', name='uq_usage_ledger_org_code_period')
    )
    op.create_index('ix_usage_ledger_org_code', 'usage_ledgers', ['organization_id', 'entitlement_code'], unique=False)
    op.create_index('ix_usage_ledger_organization_id', 'usage_ledgers', ['organization_id'], unique=False)
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier_profile_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('tier_version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('billing_status', sa.String(length=30), nullable=True))
        batch_op.create_index('ix_organization_tier_profile_id', ['tier_profile_id'], unique=False)
        batch_op.create_foreign_key('fk_organizations_tier_profile_id_tier_profiles', 'tier_profiles', ['tier_profile_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_organizations_tier_profile_id_tier_profiles', type_='foreignkey')
        batch_op.drop_index('ix_organization_tier_profile_id')
        batch_op.drop_column('billing_status')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('tier_version')
        batch_op.drop_column('tier_profile_id')
    op.drop_index('ix_usage_ledger_organization_id', table_name='usage_ledgers')
    op.drop_index('ix_usage_ledger_org_code', table_name='usage_ledgers')
    op.drop_table('usage_ledgers')
    op.drop_index('ix_onboarding_state_organization_id', table_name='onboarding_states')
    op.drop_table('onboarding_states')
    op.drop_index('ix_entitlements_organization_id', table_name='entitlements')
    op.drop_index('ix_entitlements_org_code', table_name='entitlements')
    op.drop_table('entitlements')
    op.drop_index('ix_tier_profile_tier_code', table_name='tier_profiles')
    op.drop_table('tier_profiles')
    # ### end Alembic commands ###
